### ISSUE TITLE
Discussion: Split check-kube-pods-pending into two checks?

### ISSUE THREAD

**Issue by nyxcharon** [sensu-plugins/sensu-plugins-kubernetes#25]
When I originally wrote check-kube-pods-pending, it was meant to simply look out for pods that have issues in general. Going forward, I feel like it makes sense to split this into two checks, check-kube-pods-pending for checking pending pods, as well as check-kube-pods-restarting and move the restart check logic into that. I can see separate use cases for each

Adding a flag into the original check to do this just feels hacky and in my mind doesn't really make sense, if you are going to do that you might as well separate the checks.

I wanted to post this and get some feedback, if people think it's a good idea i'll separate them and send a PR.

Summary:
- check-kube-pods-pending check for pending pods
- check-kube-pods-restarting check for restarting pods

**Comment by sstarcher** [comment]
sounds good to me

**Comment by ajohnstone** [comment]
this can be close right?
