### ISSUE TITLE
Don't trigger check-kube-nodes-ready alert if node is set as unschedulable

### ISSUE THREAD

**Issue by tg90nor** [sensu-plugins/sensu-plugins-kubernetes#38]
I don't think it makes sense to trigger an alert for a node that is not ready if it is set as unschedulable.

I will make a PR if you think this is reasonable. I can make this a command line parameter if that is preferrable.

**Comment by majormoses** [comment]
I don't know as much as I should about kubernetes as I probably should, is there any use case where someone might want to be alerted for this? If there is a doubt then I would suggest making this parameterized behavior.

**Comment by majormoses** [comment]
@jaxxstorm any thoughts?

**Comment by jaxxstorm** [comment]
No this seems reasonable. Good idea!

**Comment by majormoses** [comment]
Awaiting PR then.

**Comment by majormoses** [comment]
closed via #40
