### ISSUE TITLE
Checks fail when SSL is enabled and authentication is required

### ISSUE THREAD

**Issue by mickfeech** [sensu-plugins/sensu-plugins-kubernetes#9]
Checks fail if SSL is enable for API server and if authentication is required

**Comment by mickfeech** [comment]
#11

**Comment by mickfeech** [comment]
Pull request #14

**Comment by GKTheOne** [comment]
Needs CA + bearer token file support as well though. (preferably with the default locations "/var/run/secrets/kubernetes.io/serviceaccount/*") :)

Ruby is not one of my usual languages :(
